BEGIN;
CREATE OR REPLACE FUNCTION security.current_workspace_id() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('app.workspace_id', true),'')::uuid
$$;
CREATE OR REPLACE FUNCTION security.workspace_access(row_workspace_id uuid) RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT row_workspace_id = security.current_workspace_id()
$$;
ALTER TABLE public.api_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_credentials FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS api_credentials_workspace_policy ON public.api_credentials;
CREATE POLICY api_credentials_workspace_policy ON public.api_credentials USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.assignment_checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignment_checkpoints FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS assignment_checkpoints_workspace_policy ON public.assignment_checkpoints;
CREATE POLICY assignment_checkpoints_workspace_policy ON public.assignment_checkpoints USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS assignments_workspace_policy ON public.assignments;
CREATE POLICY assignments_workspace_policy ON public.assignments USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS audit_events_workspace_policy ON public.audit_events;
CREATE POLICY audit_events_workspace_policy ON public.audit_events USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.browser_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.browser_sessions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS browser_sessions_workspace_policy ON public.browser_sessions;
CREATE POLICY browser_sessions_workspace_policy ON public.browser_sessions USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.credit_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_reservations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS credit_reservations_workspace_policy ON public.credit_reservations;
CREATE POLICY credit_reservations_workspace_policy ON public.credit_reservations USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.delegated_token_jtis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delegated_token_jtis FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS delegated_token_jtis_workspace_policy ON public.delegated_token_jtis;
CREATE POLICY delegated_token_jtis_workspace_policy ON public.delegated_token_jtis USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.disputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disputes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS disputes_workspace_policy ON public.disputes;
CREATE POLICY disputes_workspace_policy ON public.disputes USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.entitlement_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.entitlement_snapshots FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS entitlement_snapshots_workspace_policy ON public.entitlement_snapshots;
CREATE POLICY entitlement_snapshots_workspace_policy ON public.entitlement_snapshots USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.file_upload_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.file_upload_sessions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS file_upload_sessions_workspace_policy ON public.file_upload_sessions;
CREATE POLICY file_upload_sessions_workspace_policy ON public.file_upload_sessions USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.files FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS files_workspace_policy ON public.files;
CREATE POLICY files_workspace_policy ON public.files USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.fraud_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fraud_cases FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS fraud_cases_workspace_policy ON public.fraud_cases;
CREATE POLICY fraud_cases_workspace_policy ON public.fraud_cases USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.idempotency_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.idempotency_records FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS idempotency_records_workspace_policy ON public.idempotency_records;
CREATE POLICY idempotency_records_workspace_policy ON public.idempotency_records USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS invoices_workspace_policy ON public.invoices;
CREATE POLICY invoices_workspace_policy ON public.invoices USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.outbox_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbox_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS outbox_events_workspace_policy ON public.outbox_events;
CREATE POLICY outbox_events_workspace_policy ON public.outbox_events USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.promotion_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotion_reservations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS promotion_reservations_workspace_policy ON public.promotion_reservations;
CREATE POLICY promotion_reservations_workspace_policy ON public.promotion_reservations USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS quotes_workspace_policy ON public.quotes;
CREATE POLICY quotes_workspace_policy ON public.quotes USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.results FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS results_workspace_policy ON public.results;
CREATE POLICY results_workspace_policy ON public.results USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS subscriptions_workspace_policy ON public.subscriptions;
CREATE POLICY subscriptions_workspace_policy ON public.subscriptions USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.task_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_attempts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS task_attempts_workspace_policy ON public.task_attempts;
CREATE POLICY task_attempts_workspace_policy ON public.task_attempts USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.task_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_revisions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS task_revisions_workspace_policy ON public.task_revisions;
CREATE POLICY task_revisions_workspace_policy ON public.task_revisions USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.task_state_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_state_history FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS task_state_history_workspace_policy ON public.task_state_history;
CREATE POLICY task_state_history_workspace_policy ON public.task_state_history USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tasks_workspace_policy ON public.tasks;
CREATE POLICY tasks_workspace_policy ON public.tasks USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.usage_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_events FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS usage_events_workspace_policy ON public.usage_events;
CREATE POLICY usage_events_workspace_policy ON public.usage_events USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.verification_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_votes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS verification_votes_workspace_policy ON public.verification_votes;
CREATE POLICY verification_votes_workspace_policy ON public.verification_votes USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verifications FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS verifications_workspace_policy ON public.verifications;
CREATE POLICY verifications_workspace_policy ON public.verifications USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.webhook_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_deliveries FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS webhook_deliveries_workspace_policy ON public.webhook_deliveries;
CREATE POLICY webhook_deliveries_workspace_policy ON public.webhook_deliveries USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.webhook_endpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_endpoints FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS webhook_endpoints_workspace_policy ON public.webhook_endpoints;
CREATE POLICY webhook_endpoints_workspace_policy ON public.webhook_endpoints USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.websocket_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.websocket_connections FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS websocket_connections_workspace_policy ON public.websocket_connections;
CREATE POLICY websocket_connections_workspace_policy ON public.websocket_connections USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.websocket_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.websocket_subscriptions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS websocket_subscriptions_workspace_policy ON public.websocket_subscriptions;
CREATE POLICY websocket_subscriptions_workspace_policy ON public.websocket_subscriptions USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.workspace_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_invitations FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS workspace_invitations_workspace_policy ON public.workspace_invitations;
CREATE POLICY workspace_invitations_workspace_policy ON public.workspace_invitations USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.workspace_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_members FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS workspace_members_workspace_policy ON public.workspace_members;
CREATE POLICY workspace_members_workspace_policy ON public.workspace_members USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.workspace_routing_fairness ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_routing_fairness FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS workspace_routing_fairness_workspace_policy ON public.workspace_routing_fairness;
CREATE POLICY workspace_routing_fairness_workspace_policy ON public.workspace_routing_fairness USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.ledger_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ledger_accounts FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ledger_accounts_workspace_policy ON public.ledger_accounts;
CREATE POLICY ledger_accounts_workspace_policy ON public.ledger_accounts USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.ledger_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ledger_transactions FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ledger_transactions_workspace_policy ON public.ledger_transactions;
CREATE POLICY ledger_transactions_workspace_policy ON public.ledger_transactions USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
ALTER TABLE public.ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ledger_entries FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ledger_entries_workspace_policy ON public.ledger_entries;
CREATE POLICY ledger_entries_workspace_policy ON public.ledger_entries USING (security.workspace_access(workspace_id)) WITH CHECK (security.workspace_access(workspace_id));
COMMIT;
