import 'dart:convert';

import 'semantic_chunk_engine.dart';

/// Code-owned provenance wrapper for map/reduce partials.
///
/// The model never emits [sourceChunkIndexes] or [processedCharRanges]; the
/// pipeline assigns and merges them in code.
class ReducePartialEnvelope {
  const ReducePartialEnvelope({
    required this.sourceChunkIndexes,
    required this.processedCharRanges,
    required this.partial,
  });

  final List<int> sourceChunkIndexes;
  final List<ProcessedRange> processedCharRanges;
  final Map<String, dynamic> partial;

  factory ReducePartialEnvelope.fromMapStage({
    required SemanticChunk chunk,
    required Map<String, dynamic> partial,
  }) =>
      ReducePartialEnvelope(
        sourceChunkIndexes: [chunk.chunkIndex],
        processedCharRanges: [chunk.processedRange],
        partial: partial,
      );

  /// Unions provenance from [sources] after a merge; never regenerated by model.
  factory ReducePartialEnvelope.mergeGroup(
    List<ReducePartialEnvelope> sources,
    Map<String, dynamic> mergedPartial,
  ) {
    final indexes = <int>[];
    final ranges = <ProcessedRange>[];
    for (final source in sources) {
      indexes.addAll(source.sourceChunkIndexes);
      ranges.addAll(source.processedCharRanges);
    }
    indexes.sort();
    return ReducePartialEnvelope(
      sourceChunkIndexes: indexes,
      processedCharRanges: ranges,
      partial: mergedPartial,
    );
  }

  /// Synthetic envelope for tests that pass bare partial maps without chunk metadata.
  factory ReducePartialEnvelope.testSynthetic({
    required int chunkIndex,
    required Map<String, dynamic> partial,
  }) =>
      ReducePartialEnvelope(
        sourceChunkIndexes: [chunkIndex],
        processedCharRanges: [
          ProcessedRange(startChar: chunkIndex * 1000, endChar: chunkIndex * 1000 + 500),
        ],
        partial: partial,
      );

  static List<ReducePartialEnvelope> wrapLegacyPartials(
    List<Map<String, dynamic>> partials,
  ) =>
      [
        for (var index = 0; index < partials.length; index++)
          ReducePartialEnvelope.testSynthetic(
            chunkIndex: index,
            partial: partials[index],
          ),
      ];

  /// Single serialization path for budget evaluation and inference prompts.
  static String encodeForPrompt(List<ReducePartialEnvelope> envelopes) =>
      jsonEncode(envelopes.map((envelope) => envelope.toJson()).toList());

  Map<String, dynamic> toJson() => {
    'sourceChunkIndexes': sourceChunkIndexes,
    'processedCharRanges': processedCharRanges.map((range) => range.toJson()).toList(),
    'partial': partial,
  };
}
