apiVersion: edgemint.io/v1
kind: ServiceDefinition
metadata:
  name: result
  version: 2.0.0
  status: active
  owners:
  - ml-platform
spec:
  service: result
  ownerTeam: ml-platform
  dataOwnership:
  - result
  synchronousDependencies: []
  asynchronousEventsProduced: []
  sloRef: SLOPolicy/platform-slo-v2@2.0.0
  deploymentClass: stateless
  piiAccess: restricted
