apiVersion: edgemint.io/v1
kind: ServiceDefinition
metadata:
  name: reward
  version: 2.0.0
  status: active
  owners:
  - worker-economy
spec:
  service: reward
  ownerTeam: worker-economy
  dataOwnership:
  - reward
  synchronousDependencies: []
  asynchronousEventsProduced: []
  sloRef: SLOPolicy/platform-slo-v2@2.0.0
  deploymentClass: stateless
  piiAccess: metadata_only
