#!/usr/bin/env python3
"""Generate compose.backend.yaml for local Docker stacks."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "compose.backend.yaml"

SERVICES = (
    "api-gateway",
    "event-relay",
    "identity",
    "customer",
    "file",
    "task-intake",
    "pricing",
    "router",
    "worker-gateway",
    "worker-registry",
    "result",
    "verification",
    "billing",
    "ledger",
    "reward",
    "claim",
    "fraud",
    "webhook",
    "model-registry",
    "notification",
    "operations",
)

EXPOSED_PORTS = {
    "api-gateway": "8080:8080",
    "worker-gateway": "8081:8080",
    "event-relay": "8082:8080",
    "operations": "8083:8080",
}


def service_block(name: str) -> str:
    lines = [
        f"  {name}:",
        "    <<: *backend-service",
        "    build:",
        "      context: .",
        f"      dockerfile: src/backend/services/{name}/Dockerfile",
        "      args:",
        "        PYTHON_RUNTIME_IMAGE: ${PYTHON_RUNTIME_IMAGE:-python:3.13.14-slim-bookworm}",
        "    environment:",
        "      <<: *backend-environment",
        f"      EDGEMINT_SERVICE_NAME: {name}",
    ]
    if name in EXPOSED_PORTS:
        lines.append("    ports:")
        lines.append(f'      - "{EXPOSED_PORTS[name]}"')
    return "\n".join(lines)


def main() -> None:
    header = """# Generated by tools/generate_compose_backend.py — do not edit by hand.
# Run: python tools/generate_compose_backend.py

x-backend-environment: &backend-environment
  EDGEMINT_ENVIRONMENT: development
  EDGEMINT_DATABASE_URL: postgresql+psycopg://edgemint:${POSTGRES_PASSWORD:-change-me}@postgresql:5432/${POSTGRES_DB:-edgemint}
  EDGEMINT_ALLOW_INSECURE_DEVELOPMENT_TOKENS: ${EDGEMINT_ALLOW_INSECURE_DEVELOPMENT_TOKENS:-true}
  EDGEMINT_JWT_SIGNING_SECRET: ${EDGEMINT_JWT_SIGNING_SECRET:-local-docker-jwt-secret-change-me}
  EDGEMINT_JWT_ISSUER: ${EDGEMINT_JWT_ISSUER:-edgemint-local}

x-backend-service: &backend-service
  init: true
  restart: unless-stopped
  networks: [edgemint]
  environment:
    <<: *backend-environment
  depends_on:
    postgresql-seed:
      condition: service_completed_successfully
  volumes:
    - ./dsl:/app/dsl:ro
  healthcheck:
    test:
      - CMD
      - python
      - -c
      - import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/health/live')
    interval: 15s
    timeout: 5s
    retries: 5
    start_period: 45s

services:
"""
    body = "\n\n".join(service_block(name) for name in SERVICES)
    networks = """
networks:
  edgemint:
    name: edgemint
"""
    OUTPUT.write_text(header + body + networks + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(SERVICES)} services)")


if __name__ == "__main__":
    main()
